services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080 
    depends_on:
      - db
    volumes:
      - ./HorizonConvergia/appsettings.Docker.json:/app/appsettings.json

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Docker123@"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserverdata:/var/opt/mssql

  migrator:
    image: mcr.microsoft.com/dotnet/sdk:7.0  
    volumes:
      - ./:/app
    working_dir: /app
    command: ["dotnet", "ef", "database", "update"]
    depends_on:
      - db

volumes:
  sqlserverdata:
